[package]
name = "ggmath"
version = "0.14.0"
edition = "2024"

[features]
std = []

assertions = []
debug_assertions = []
overflow_checks = []
debug_overflow_checks = []

default = ["std", "debug_assertions", "debug_overflow_checks"]

[dev-dependencies]
pastey = "0.2.0"
colored = "3.0.0"
