[package]
name = "ggmath"
readme = "README.md"
repository = "https://github.com/Noam2Stein/ggmath"

version = "0.14.0"
edition = "2024"
rust-version = "1.90.0"

description = "A math library for games and graphics with generic SIMD types."
categories = [
    "data-structures",
    "game-development",
    "graphics",
    "mathematics",
    "no-std",
]
keywords = ["math", "matrix", "simd", "vector"]
license = "MIT OR Apache-2.0"

[features]
std = []

assertions = []
debug_assertions = []
overflow_checks = []
debug_overflow_checks = []

default = ["std", "debug_assertions", "debug_overflow_checks"]

[dev-dependencies]
colored = "3.0.0"
criterion = "0.7.0"
glam = "0.30.9"
pastey = "0.2.0"
wide = "0.8.3"

[[bench]]
name = "vector_f32"
path = "benches/vector/f32.rs"
harness = false
